import React, { useState } from 'react';
import { X, Copy, Check, Printer, FileDown, Download } from 'lucide-react';
import type { DecisionAnalysis } from '@workspace/api-client-react';

interface ExportReportModalProps {
  decision: DecisionAnalysis;
  onClose: () => void;
}

export function ExportReportModal({ decision, onClose }: ExportReportModalProps) {
  const [copied, setCopied] = useState(false);
  const [format, setFormat] = useState<'markdown' | 'json' | 'executive'>('executive');

  const formattedDate = new Date(decision.createdAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const generateMarkdown = () => {
    return `# DecisionLens XAI Executive Briefing
**Scenario:** ${decision.scenarioName}  
**Date:** ${formattedDate}  
**Recommendation:** ${decision.recommendationLabel.toUpperCase()}  
**Readiness Score:** ${decision.overallScore}/100 | **Confidence:** ${decision.confidence}% (${decision.confidenceLabel})  
**Model Version:** ${decision.modelVersion || 'DecisionLens-XAI-v1.4-Hybrid'}

---

## Executive Summary
${decision.rationale}

## Operational Context
${decision.context || 'No supplementary context provided.'}

## Factor Breakdown & XAI Impact
${decision.factors
  .map(
    (f) =>
      `- **${f.label}:** Score: ${f.score}/100 | Impact: ${f.impact > 0 ? '+' : ''}${f.impact} pts (${f.direction})\n  *${f.explanation}*`
  )
  .join('\n\n')}

## Recommended Action Items
${decision.nextSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}

---
*Generated by DecisionLens XAI Decision-Support System.*
`;
  };

  const generateJson = () => {
    return JSON.stringify(decision, null, 2);
  };

  const getExportText = () => {
    if (format === 'json') return generateJson();
    return generateMarkdown();
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getExportText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="dl-modal-backdrop" onClick={onClose}>
      <div className="dl-modal-content" onClick={(e) => e.stopPropagation()}>
        <div className="dl-modal-head">
          <div>
            <h2 style={{ font: '600 20px var(--app-font-serif)', margin: 0 }}>
              Export Decision Briefing
            </h2>
            <div style={{ fontSize: '11px', color: '#6b7e79', marginTop: '3px' }}>
              {decision.scenarioName}
            </div>
          </div>
          <button
            className="dl-btn dl-btn-quiet dl-icon-btn"
            onClick={onClose}
            style={{ borderRadius: '50%' }}
          >
            <X size={15} />
          </button>
        </div>

        {/* Format Selector */}
        <div style={{ display: 'flex', gap: '8px', marginBottom: '16px' }}>
          {(['executive', 'markdown', 'json'] as const).map((fmt) => (
            <button
              key={fmt}
              onClick={() => setFormat(fmt)}
              className={`dl-filter ${format === fmt ? 'active' : ''}`}
            >
              {fmt === 'executive' ? 'Executive Report' : fmt === 'markdown' ? 'Markdown' : 'Raw JSON'}
            </button>
          ))}
        </div>

        {/* Content Box */}
        <div className="dl-modal-pre">
          <code>{getExportText()}</code>
        </div>

        {/* Action Buttons */}
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px', marginTop: '20px' }}>
          <button className="dl-btn dl-btn-quiet" onClick={handlePrint}>
            <Printer size={13} /> Print / Save PDF
          </button>
          <button className="dl-btn dl-btn-primary" onClick={handleCopy}>
            {copied ? <Check size={13} /> : <Copy size={13} />}
            {copied ? 'Copied to Clipboard' : 'Copy Content'}
          </button>
        </div>
      </div>
    </div>
  );
}
